# Generated by Django 5.2.4 on 2025-09-11 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-bid_amount']},
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together=set(),
        ),
    ]
