# Generated by Django 5.2.4 on 2025-08-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsupload',
            name='bid_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
