# Generated by Django 5.2.4 on 2025-08-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_itemsupload_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsupload',
            name='is_approved',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
