# Generated by Django 5.2.4 on 2025-09-11 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_bid_options_rename_create_at_bid_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='created_at',
            new_name='create_at',
        ),
    ]
