# Generated by Django 5.2.4 on 2025-08-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_itemsupload_bid_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsupload',
            name='bid_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
