# Generated by Django 5.2.4 on 2025-08-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_itemsupload_bid_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsupload',
            name='bid_code',
        ),
    ]
