name: ci

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' # Deploy only from the main branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub token to push to the repository
          publish_dir: ./build # Directory containing the built files
          user_name: "Your Name"
          user_email: "your-email@example.com"
          allow_empty_commit: true # Allow empty commit (useful for first deploy)
          force_orphan: true # Force creating an orphan branch (no history)

